version: "3.8"

services:
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5001:8080

  client:
    build: ./client
    volumes:
      - './client/src:/app/src'
      - './client/public:/app/public'
    ports:
      - 3001:3000
    depends_on:
      - server
